### ISSUE TITLE
老哥继续更新啊~ 关注！

### ISSUE THREAD

**Issue by JianGuoPaPa** [Abyssness/website-Dome#1]

**Comment by Fuarmy** [comment]
你可以取关了，我都不知道什么时候继续更新

**Comment by Fuarmy** [comment]
你可以取关了，我也不知道什么时候继续更新

**Comment by changly** [comment]
> 你可以取关了，我也不知道什么时候继续更新

有联系方式吗 请教一些问题

**Comment by changly** [comment]
> 你可以取关了，我也不知道什么时候继续更新

或者你加我一下 qq同wx 1907696512

**Comment by Abyssness** [comment]
> > 你可以取关了，我也不知道什么时候继续更新
> 
> -大人家和同名同上 qqwx 1907696512

什么问题？
